### ISSUE TITLE
Compatibility with TYPO3 7.6

### ISSUE THREAD

**Issue by wimr0001** [xperseguers/t3ext-tscobj#7]
In Typo3 7.6, Frontend, I encounter the error class "tslib_pibase" not found in class.tx_tscobj_pi1.php on line 45.
In the ext_emconf.php is set "'typo3' => '4.5.0-7.6.99', so there was no warning at installing the extension.
Any idea when the extension is adjusted to typo3 7.6?

**Comment by xperseguers** [comment]
In fact, this extension is not compatible with TYPO3 7 LTS.

Migrating the "plugin" part is very easy and should have been done partly already if you use the git version. However migrating the TS tree selector is a bit more complex.

I cannot tell you when this extension will be adjusted to TYPO3 7.6 since I took it over a while ago when I needed to make it compatible for TYPO3 6.2 but now I don't use it anymore so I don't think I'll invest energy on my scarse spare time for an extension I don't need anymore. However I gladly accept pull requests.

**Comment by rosimittermeier** [comment]
there is a new version of page_php_content: 
https://typo3.org/extensions/repository/view/pe_pagephpcontentelement
(offically it is only up to 7.5. but it works with 7.6.3, too.)

You can use is without typo3-skript but it works quite as tscobj works. Here is a manual: 
https://www.public-enragement.com/2015/10/02/typo3-ext-pe-page-php-content/

I realised my scripts in typo3_7_LTS:
1. install Extension
2. (a) in the site tree i inserted folders and (b) in the folders pagephpcontent-elements
3. in these elements (2.b) i inserted a php-script which includes a php-script on the server (the ones which had been included by typoscript for tscobj. <?php ... include ...; ?>)
4. on the pages i inserted elements form the (a) plugin type and (b) i selected pagephpcontent plugin on the secon tab and (c) then i selected the folder (cf. 2.a) whith the php-script-with-the-include-script inside (2.b).
5. thats all
6. you should deactivate the cache for the page with the pagephpcontent-plugin.

[[keywords: include php scripts typo3 7.6 7LTS extension php_script]]

**Comment by rosimittermeier** [comment]
but tscobj has been a better solution!

**Comment by wimr0001** [comment]
Thank you for your answers. In the meantime I developed my own extension with the same result as "tscobj". I have not finished the job completely; in BE on the page view the name of the typoscript object has to be presented.
